### ISSUE TITLE
Could this be a routing issue?

### ISSUE THREAD

**Issue by VirtualDOMinic** [fac-14/CJKO-autocomplete#38]
Currently trying to look into this now, will update with comments, but the title is my first thought!

Amusing, useful, comment though

https://github.com/fac-14/CJKO-autocomplete/blob/2d7b151d528a65d0b7e0e335bac001633e5a5dcf/public/index.html#L10-L14

**Comment by sunuwars** [comment]
:smile::smile::smile:
