### ISSUE TITLE
Happy to try and help you get this hosted 🕺🏻

### ISSUE THREAD

**Issue by developess** [fac-14/CJKO-autocomplete#59]
It might be a problem with your package.json - your 'main file' is listed as the default - index.js. It should be server.js. 

Also adding a Procfile may help - it seemed to fix our issue. 

#35 #42

**Comment by njons** [comment]
yay! lets get these dinos online!!!  🎉

**Comment by Zeanort** [comment]
Just managed to do it :+1:  Thanks for the offer to help.
